### ISSUE TITLE
finite automata class

### ISSUE THREAD

**Issue by AmirHossein812002** [AmirHossein812002/Regex2FA#1]
**tasks:**

- [x]  create a finite automata class
- [x] create a function that validate regular expression
- [x] create a function that parse a regular expression and converting it to finite automata
