### ISSUE TITLE
toMinimizedDFA function

### ISSUE THREAD

**Issue by AmirHossein812002** [AmirHossein812002/Regex2FA#4]
**tasks:**

- [x]  implementing toMinimizedDFA function
- [x] completing isEqual function with comparing two minimzedDFAs
- [x] adding miniDFA showing in automata box
